sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start Creation an image with dockerfile"
  - docker build -t sglee65/docker-react-test-app -f Dockerfile.dev .

script:
  - docker run -e CI=true sglee65/docker-react-test-app npm run test -- --coverage

after_success:
  - echo "Test Success"
